#!/bin/sh

if [ ! -f qlmlist ]
then
    echo qlmlist must be in current directory
    exit 1
fi

if [ ! -x lmutil ]; then
    chmod a+x lmutil
fi

echo "Listing status of QualNet licenses ... (this may take 10-20 seconds)"
echo

./lmutil lmstat -c .. -f
